apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-backend-deployment
spec:
  selector:
    matchLabels:
      app: portal-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-backend
    spec:
      containers:
        - image: robekeane/portal-backend:0.1
          name: portal-backend-con
